name: app_bloody
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  firebase_messaging: ^5.1.6
  google_maps_flutter: ^0.5.21+8
  path_provider: ^0.5.0+1
  flutter_local_notifications: ^0.8.4
shared_preferences: ^0.5.4+5

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #  - images/a_dot_ham.jpeg


